### ISSUE TITLE
Xcode9适配？

### ISSUE THREAD

**Issue by highlystuff** [everettjf/ostrace#1]
demo工程在Xcode9上编不过

**Comment by everettjf** [comment]
你编译的错误是什么，贴一下，我刚测试可以编译过呀

**Comment by highlystuff** [comment]
Unknown type name 'RegState'

**Comment by LiLejia** [comment]
Looks all good to me on Xcode 9.0.

**Comment by everettjf** [comment]
@highlystuff 第二个demo只能编译arm64的真机。
