### ISSUE TITLE
在苹果6真机上运行，在沙盒里面没有Library/appletracedata目录

### ISSUE THREAD

**Issue by idewindy** [everettjf/ostrace#2]
不管是通过MonkeyDev还是工程依赖方式都不行，工程都能正常运行

**Comment by everettjf** [comment]
发下例子？

**Comment by idewindy** [comment]
随便建立一个工程都行，我建立一个空工程，然后拖入appletrace.xcodeproj，配置下，在手机上运行，在沙盒里面没有appletracedata目录，我的QQ是1770421128，我给你发下工程。

**Comment by everettjf** [comment]
参考这个图片：

![image](http://everettjf.com/media/15060104195090.jpg)


@idewindy 加我微信 everettjf

**Comment by everettjf** [comment]
更新了下wiki。简单几个faq。
https://github.com/everettjf/AppleTrace/wiki
