### ISSUE TITLE
你好 怎么使用呢?

### ISSUE THREAD

**Issue by MoShenGuo** [everettjf/ostrace#3]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/21171688/69324916-4620ea00-0c84-11ea-96a4-c7b6e5e31c15.png">
你好 报错了,怎么使用呢?是监控什么指标呢?还望大神指教一下

**Comment by everettjf** [comment]
真机。看下我的博客文章哈

________________________________
发件人: APP performance data monitoring <notifications@github.com>
发送时间: Thursday, November 21, 2019 5:28:34 PM
收件人: everettjf/AppleTrace <AppleTrace@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [everettjf/AppleTrace] 你好 怎么使用呢? (#3)


[image]<https://user-images.githubusercontent.com/21171688/69324916-4620ea00-0c84-11ea-96a4-c7b6e5e31c15.png>

你好 报错了,怎么使用呢?是监控什么指标呢?还望大神指教一下

―

**Comment by MoShenGuo** [comment]
你好 你的博客链接是什么呢?谢谢

**Comment by everettjf** [comment]
![image](https://user-images.githubusercontent.com/1665109/69434885-78f8da00-0d79-11ea-9757-a5b9afcbbeba.png)
