### ISSUE TITLE
求助无法安装

### ISSUE THREAD

**Issue by codesourse** [everettjf/ostrace#4]
source 'https://github.com/everettjf/MonkeyDevSpecs.git'
这个是闭源的
☺  pod install                                                                                                           
Analyzing dependencies
Downloading dependencies
Installing AppleTrace (1.0.1)

[!] Error installing AppleTrace
[!] /usr/bin/git clone https://github.com/everettjf/AppleTrace.git /var/folders/tb/6pfzm13902n36z4ysjd7046m0000gn/T/d20200312-27037-ubqno8 --template= --single-branch --depth 1 --branch 1.0.1

Cloning into '/var/folders/tb/6pfzm13902n36z4ysjd7046m0000gn/T/d20200312-27037-ubqno8'...
warning: Could not find remote branch 1.0.1 to clone.
fatal: Remote branch 1.0.1 not found in upstream origin

**Comment by everettjf** [comment]
现在到这里了 https://github.com/AloneMonkey/MonkeyDevSpecs
